platform :ios, '9.0'

target 'PopTest' do
  use_frameworks!

  pod 'pop', '~> 1.0'

  target 'PopTestTests' do
    inherit! :search_paths

  end

  target 'PopTestUITests' do
    inherit! :search_paths

  end

end
